import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Uploader from '../components/custom_uploader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [name, setName] = useState('');

  async function getFromAPI() {
    const result = await (await fetch('/api/hello')).json()
    console.log(result)
    setName(result.name)
  }

  useEffect(() => {
    getFromAPI()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
          Kavach Testing (please upload PNG only)
          </p>

        </div>
        <div> 
        <p>
          1. upload png file
          </p><p>
          2. set access control
          </p>
        </div>
       
    <Uploader />
    
{/* 
    <video controls autoplay name="media">
      <source src="https://gateway.lighthouse.storage/ipfs/QmdQN5R6F8mU4X8qZ3bUXCnCRNKCeaRZ1L2YjPKrbaEmh8" type="video/webm"/>
    </video>
   */}

      </main>
    </>
  )
}
