import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Uploader from '../components/uploader'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [name, setName] = useState('');

  async function getFromAPI() {
    const result = await (await fetch('/api/hello')).json()
    console.log(result)
    setName(result.name)
  }

  useEffect(() => {
    getFromAPI()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            {name} 
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

       
    <Uploader />

  

        <div className={styles.grid}>
          <a
            href="encrypt"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Encrypt <span>-&gt;</span>
            </h2>
          </a>

          <a
            href="decrypt"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Decrypt <span>-&gt;</span>
            </h2>
          </a>

          
        </div>
      </main>
    </>
  )
}
